name: Warn PR from forked repository

on:
  # Intentional: forked repository doesn't have write permission to the base repository.
  pull_request_target:
    types: [opened]

jobs:
  comment-on-forked-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Add a comment if PR is from a fork
#        if: ${{ github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name }}
        run: |
          PR_AUTHOR=${{ github.event.pull_request.user.login }}
          COMMENT=":warning: Attention @$PR_AUTHOR!
            Thank you for your interest in contributing to this repository.

            This repository primarily exists to convert publicly available LINE APIs into OpenAPI YAML, making it easier for developers to access the features.
            Therefore, it is not intended for open contributions by editing files in this repository.

            Please start by creating an issue and discussing it there. You may close this pull request and create an issue instead.

            ==
            If you are an employee participating in this organization, please push branches directly to this repository to create PR, instead of using a forked repository.
          "
          
          gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT"
